load("@rules_cc//cc:cc_binary.bzl", "cc_binary")
load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_test.bzl", "cc_test")
load("@rules_shell//shell:sh_test.bzl", "sh_test")

cc_library(
    name = "main",
    srcs = ["cpp/main.cpp"],
    deps = [
        "//thirdparty/catch2",
    ],
)

cc_test(
    name = "tests",
    size = "small",
    srcs = glob(
        [
            "cpp/**/*.cpp",
            "cpp/**/*.hpp",
        ],
        exclude = [
            "cpp/main.cpp",
            "cpp/MulticastTest.cpp",
        ],
    ),
    deps = [
        ":main",
        "//thirdparty/catch2",
        "//wpinet",
        "//wpiutil:wpiutil-testlib",
    ],
)

cc_binary(
    name = "MulticastTest_bin",
    testonly = True,
    srcs = ["cpp/MulticastTest.cpp"],
    deps = [
        ":main",
        "//thirdparty/catch2",
        "//wpinet",
    ],
)

# Needs an mDNS daemon. On Linux, multicast_test.sh starts avahi if none is
# running.
sh_test(
    name = "MulticastTest",
    size = "small",
    srcs = ["multicast_test.sh"],
    args = ["$(rootpath :MulticastTest_bin)"],
    data = [":MulticastTest_bin"],
)
